export { default as Login } from './Login/Login'
export { default as Main } from './Main/Main'
export { default as Bills } from './Bills/Bills'
export { default as Employee } from './Employee/Employee'
export { default as Products } from './Products/Products'
export { default as List } from './List/List'
export { default as  OrderStatus } from './OrderStatus/OrderStatus'